<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gkillare-win87" failures="1" tests="29" name="testcases.TC_US_VoidOfSale" time="997.780" errors="0" timestamp="2024-06-19T12:24:38 IST" skipped="0">
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard12" time="31.188"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard07" time="27.931"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard09" time="38.717"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard08" time="31.875"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard01" time="30.597"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard16" time="37.368"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard01" time="35.836"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard05" time="37.132"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard18" time="38.998"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard16" time="31.319"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard11" time="43.931"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard15" time="35.387"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard06" time="29.078"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard19" time="31.045"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard14" time="38.523"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard17" time="41.526"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard02" time="32.950"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard19" time="30.530">
    <failure message="We are not getting ResponseText as APPROVAL or VALIDATION [null,,0615769852310135,I,21,,VID,null,0.00,INCORRECT PIN,20006,210241710947974528,000000000000000000,000000,0615769852310135,AID:A0000000980840,AID:A0000000980840] expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: We are not getting ResponseText as APPROVAL or VALIDATION [null,,0615769852310135,I,21,,VID,null,0.00,INCORRECT PIN,20006,210241710947974528,000000000000000000,000000,0615769852310135,AID:A0000000980840,AID:A0000000980840] expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at base.BaseClass.performSaleTransaction(BaseClass.java:213)
at testcases.TC_US_VoidOfSale.TestCard19(TC_US_VoidOfSale.java:384)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestCard19 -->
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard10" time="38.748"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard13" time="29.739"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard13" time="28.999"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard03" time="34.434"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard21" time="36.047"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard15" time="35.735"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard12" time="35.782"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard06" time="27.661"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard20" time="35.357"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard04" time="33.493"/>
  <testcase classname="testcases.TC_US_VoidOfSale" name="TestCard07" time="37.854"/>
</testsuite> <!-- testcases.TC_US_VoidOfSale -->
